[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/javascript"

[build] 
  base = "client"
  publish = "client/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200